name: CI

on:
  pull_request:
    branches: ["master", "main", "develop"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main", "develop"]
    paths-ignore: ["docs/**"]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          cache: true
          flutter-version: 3.29.0

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

  build:
    needs: [analyze]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          cache: true
          flutter-version: 3.29.0

      - name: Install dependencies
        run: flutter pub get

      - name: Build Project
        run: flutter build apk
